// ignore_for_file: prefer_const_literals_to_create_immutables, prefer_const_constructors

import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:flip_card/flip_card.dart'; // Import the new package
import '../theme/colors.dart';

class AboutUsPage extends StatelessWidget {
  const AboutUsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 1200),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                //Main Title
                const Text(
                  "About Sniffra",
                  style: TextStyle(
                    fontSize: 48,
                    fontWeight: FontWeight.bold,
                    color: AppColors.primaryDark,
                  ),
                ),
                const SizedBox(height: 24),

                //Team Motivation / Mission Section
                const Text(
                  "Our Mission",
                  style: TextStyle(
                    fontSize: 32,
                    fontWeight: FontWeight.w600,
                    color: AppColors.primaryDark,
                  ),
                ),
                const SizedBox(height: 16),
                Text(
                  "We are a group of friends and students from Central Washington University passionate about building a more transparent and trustworthy internet. In the age of AI, it's becoming harder to distinguish authentic, human-created content from that generated by a machine. Sniffra is our answer. We believe that by empowering a community of users to collectively identify and tag web content, we can bring a new layer of clarity to the digital world. This project is born from our shared belief in collaboration, open information, and the power of the crowd to create a better online experience for everyone.",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 18,
                    color: AppColors.primaryDark.withOpacity(0.8),
                    height: 1.5,
                  ),
                ),
                const SizedBox(height: 48),
                const Divider(thickness: 1.5),
                const SizedBox(height: 48),

                //Meet the Team Section
                const Text(
                  "Meet the Team",
                  style: TextStyle(
                    fontSize: 32,
                    fontWeight: FontWeight.w600,
                    color: AppColors.primaryDark,
                  ),
                ),
                const SizedBox(height: 32),

                Wrap(
                  spacing: 24.0,
                  runSpacing: 24.0,
                  alignment: WrapAlignment.center,
                  children: [
                    TeamMemberCard(
                      name: "Alex Boyce",
                      role: "Co-Founder",
                      bio:
                          "Alex Boyce is the visionary behind Sniffra, passionate about solving modern problems utilizing today's resources.",
                      imageUrl: "images/alexheadshot.jpg",
                      githubUrl: "https://github.com/nood-leog",
                      linkedinUrl: "https://www.linkedin.com/in/nood-leog/",
                      favoriteGames: const [
                        "Counter-Strike",
                        "Factorio",
                        "Cities: Skylines",
                        "Minecraft",
                      ],
                    ),
                    TeamMemberCard(
                      name: "Oscar Chinbat",
                      role: "Co-Founder",
                      bio: "Oscar handles the project's architecture and backend systems, ensuring everything runs smoothly.",
                      imageUrl: "https://i.pravatar.cc/150?img=3", // Placeholder
                      githubUrl: "https://github.com/",
                      linkedinUrl: "https://linkedin.com/in/",
                      favoriteGames: const ["League of Legends", "Valorant"],
                    ),
                    TeamMemberCard(
                      name: "Jay Heo",
                      role: "Co-Founder",
                      bio: "Jay is the master of data, managing the database and API integrations for Sniffra.",
                      imageUrl: "https://i.pravatar.cc/150?img=11", // Placeholder
                      githubUrl: "https://github.com/",
                      linkedinUrl: "https://linkedin.com/in/",
                      favoriteGames: const ["League of Legends", "Valorant"],
                    ),
                    TeamMemberCard(
                      name: "Alex Rise",
                      role: "Co-Founder",
                      bio: "Alex Rise focuses on the core browser extension, bringing Sniffra's functionality to life.",
                      imageUrl: "https://i.pravatar.cc/150?img=5", // Placeholder
                      githubUrl: "https://github.com/",
                      linkedinUrl: "https://linkedin.com/in/",
                      favoriteGames: const ["League of Legends", "Valorant"],
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

// --- REBUILT TeamMemberCard WIDGET ---
// Now uses FlipCard for the animation

class TeamMemberCard extends StatelessWidget {
  final String name;
  final String role;
  final String bio;
  final String imageUrl;
  final String githubUrl;
  final String linkedinUrl;
  final List<String>? favoriteGames;

  const TeamMemberCard({
    super.key,
    required this.name,
    required this.role,
    required this.bio,
    required this.imageUrl,
    required this.githubUrl,
    required this.linkedinUrl,
    this.favoriteGames,
  });

  Future<void> _launchURL(String url) async {
    final uri = Uri.parse(url);
    if (!await launchUrl(uri)) {
      throw 'Could not launch $url';
    }
  }

  @override
  Widget build(BuildContext context) {
    final bool canFlip = favoriteGames != null && favoriteGames!.isNotEmpty;

    // The main widget is now FlipCard
    return FlipCard(
      // Disable flipping if there are no games
      flipOnTouch: canFlip,
      // The front of the card
      front: _buildCardFace(isFront: true),
      // The back of the card (easter egg)
      back: canFlip ? _buildCardFace(isFront: false) : const SizedBox(),
    );
  }

  // A helper method to build the content for either face of the card
  Widget _buildCardFace({required bool isFront}) {
    // The main container for styling
    return Container(
      width: 280,
      height: 360, // A fixed height helps the flip animation
      padding: const EdgeInsets.all(20.0),
      decoration: BoxDecoration(
        color: isFront ? Colors.white : AppColors.primaryDark,
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.08),
            blurRadius: 10,
            offset: const Offset(0, 4),
          ),
        ],
      ),
      child: isFront ? _buildFrontContent() : _buildBackContent(),
    );
  }

  // Builds the content for the front (bio, socials)
  Widget _buildFrontContent() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        CircleAvatar(
          radius: 50,
          backgroundImage: imageUrl.startsWith('http')
              ? NetworkImage(imageUrl)
              : AssetImage(imageUrl) as ImageProvider,
          backgroundColor: AppColors.primaryLight,
        ),
        const SizedBox(height: 16),
        Text(
          name,
          style: const TextStyle(
            fontSize: 22,
            fontWeight: FontWeight.bold,
            color: AppColors.primaryDark,
          ),
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 4),
        Text(
          role,
          style: const TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.w500,
            color: AppColors.primaryBlue, 
          ),
          textAlign: TextAlign.center,
        ),
        const SizedBox(height: 12),
        Expanded(
          child: Text(
            bio,
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 14,
              color: AppColors.primaryDark.withOpacity(0.7),
            ),
          ),
        ),
        Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            IconButton(
              icon: const FaIcon(FontAwesomeIcons.github),
              onPressed: () => _launchURL(githubUrl),
              tooltip: 'GitHub',
              color: AppColors.primaryDark.withOpacity(0.8),
            ),
            const SizedBox(width: 12),
            IconButton(
              icon: const FaIcon(FontAwesomeIcons.linkedin),
              onPressed: () => _launchURL(linkedinUrl),
              tooltip: 'LinkedIn',
              color: AppColors.primaryDark.withOpacity(0.8),
            ),
          ],
        )
      ],
    );
  }

  // Builds the content for the back (favorite games)
  Widget _buildBackContent() {
    return Column(
      children: [
        const Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            FaIcon(FontAwesomeIcons.gamepad, color: Colors.white),
            SizedBox(width: 10),
            Text(
              "Favorite Hobbies and Games",
              style: TextStyle(
                color: Colors.white,
                fontSize: 22,
                fontWeight: FontWeight.bold,
              ),
            ),
          ],
        ),
        const Divider(color: AppColors.primaryBlue, height: 24),
        Expanded(
          child: ListView.builder(
            padding: EdgeInsets.zero,
            itemCount: favoriteGames!.length,
            itemBuilder: (context, index) {
              return Padding(
                padding: const EdgeInsets.symmetric(vertical: 4.0),
                child: Text(
                  favoriteGames![index],
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: AppColors.primaryLight,
                    fontSize: 16,
                  ),
                ),
              );
            },
          ),
        ),
      ],
    );
  }
}